### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by romabulani**
- Added Signup, login and Forgot Password Flow
- picture tag for webp format of images for fast loading
ecommauth

### CODE REVIEW

**Review by varnita619 — APPROVED** [review]
UI looks clean. Good to merge

**Review by SJTGSHIVAM — APPROVED** [review]
Things look good. I saw you also made changes suggested last day that's a lot of work!
I believe we are good to merge.

**Review by ddivyansh18 — APPROVED** [review]
Nice design, looks good !

**Comment by romabulani** [comment]
> Things look good. I saw you also made changes suggested last day that's a lot of work! I believe we are good to merge.

Thankyou for suggesting resources

**Pull request merged**
