### PR TITLE
Wishlist

### PR DESCRIPTION
**Pull request by romabulani**
- some styling for cards
- covered when wishlist is not empty and empty
wishlistecomm

### CODE REVIEW

**Review by anuj-kumary — APPROVED** [review]
Looks good to me!!!

**Review by anuj-kumary — APPROVED** [review]
Looks good to me!!!

**Review by shrey27 — APPROVED** [review]
PR is good to merge

**Review by samyakshah3008 — APPROVED** [review]
Nice and clean UI! LGTM

**Review by ravikumar1002 — APPROVED** [review]
good to merge

**Pull request merged**
