### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by romabulani**
- Made Folder structure for features
- Home Page, tried to make it responsive
- Added logo for browser tab
homepageecom

### CODE REVIEW

**Review by shrey27 — APPROVED** [review]
PR is good to merge.

**Review by MurtazaBagwala07 — APPROVED** [review]
looks good to merge

**Comment by SJTGSHIVAM** [comment]
image
as we can see some of the images are having sizes over 1 mb these may add up to loading time. For now everything looks great, please consider downscaling these imaging in a later sprint.

**Review by SJTGSHIVAM — APPROVED** [review]
LGTM!

**Pull request merged**
